src/apps/home/urls.py
from django.urls import path

from apps.home.views import (
    pasal_home,
    pasal_register,
    pasal_tac,
    # dashboard
    pasal_dashboard_login,
    pasal_dashboard_logout,
    pasal_dashboard_sales,
    pasal_dashboard,
    # agg views
    pasal_dashboard_total_sales,
    pasal_dashboard_average_order_value,
    pasal_dashboard_top_customer,
    pasal_dashboard_top_selling_products,
    pasal_dashboard_total_customers,
    pasal_dashboard_total_orders,
    pasal_dashboard_transactions_list,
    pasal_dashboard_order,
    # ui
    pasal_ui_storefront_layout,
    pasal_ui_store_information,
    # products
    pasal_create_product,
    pasal_create_product_image,
    pasal_create_product_category,
    pasal_list_products,
    pasal_edit_product,
    pasal_delete_product,
    # employees
    pasal_list_employees,
    pasal_create_employees,
    pasal_edit_employee,
    pasal_delete_employee,
    # settings
    pasal_settings,
    # customers
    pasal_list_customers,
    pasal_detail_customers,
    # order
    pasal_update_order_status,
    # charts
    pasal_chart_sales_report,
    pasal_chart_category_sales_report,
)

urlpatterns = [
    path(
        "home/",
        pasal_home,
        name="pasal_home",
    ),
    path(
        "terms-and-conditions",
        pasal_tac,
        name="pasal_terms_and_conditions",
    ),
    path(
        "register/",
        pasal_register,
        name="pasal-register-tenant",
    ),
    path(
        "login/",
        pasal_dashboard_login,
        name="pasal-dashboard-login",
    ),
    path(
        "logout/",
        pasal_dashboard_logout,
        name="pasal-dashboard-logout",
    ),
    path(
        "dashboard/",
        pasal_dashboard,
        name="pasal-dashboard",
    ),
]

sales = [
    path(
        "dashboard/sales/",
        pasal_dashboard_sales,
        name="pasal-dashboard-sales",
    ),
]

products = [
    path(
        "dashboard/products/add/",
        pasal_create_product,
        name="pasal_create_product",
    ),
    path(
        "dashboard/products/list/<int:page>/",
        pasal_list_products,
        name="pasal_list_product",
    ),
    path(
        "dashboard/products/edit/<slug:slug>/",
        pasal_edit_product,
        name="pasal_edit_product",
    ),
    path(
        "dashboard/products/delete/<slug:slug>/",
        pasal_delete_product,
        name="pasal_delete_product",
    ),
    path(
        "dashboard/products/add/image/",
        pasal_create_product_image,
        name="pasal_create_product_image",
    ),
    path(
        "dashboard/products/add/category/",
        pasal_create_product_category,
        name="pasal_create_category",
    ),
]

ui = [
    path(
        "dashboard/ui/storefront/",
        pasal_ui_storefront_layout,
        name="pasal_dashboard_storefront_ui",
    ),
    path(
        "dashboard/ui/products/",
        pasal_ui_storefront_layout,
        name="pasal-dashboard-ui-product-page",
    ),
    path(
        "dashboard/storeinformation/",
        pasal_ui_store_information,
        name="pasal_store_information",
    ),
]

customers = [
    path(
        "dashboard/customers/list/",
        pasal_list_customers,
        name="pasal-list-customers",
    ),
    path(
        "dashboard/customers/<int:customer_id>/",
        pasal_detail_customers,
        name="pasal-detail-customers",
    ),
]

employees = [
    path(
        "dashboard/employees/list/",
        pasal_list_employees,
        name="list-employees",
    ),
    path(
        "employees/create/",
        pasal_create_employees,
        name="create-employees",
    ),
    path(
        "employees/<int:employee_id>/edit/",
        pasal_edit_employee,
        name="edit-employee",
    ),
    path(
        "dashboard/employees/<int:employee_id>/delete/",
        pasal_delete_employee,
        name="delete-employee",
    ),
]


order = [
    path(
        "dashboard/order/<int:order_id>/update/",
        pasal_update_order_status,
        name="update_order_status",
    ),
]


charts = [
    path(
        "dashboard/charts/sales-report/",
        pasal_chart_sales_report,
        name="pasal_charts_sales_report",
    ),
    path(
        "dashboard/charts/category-sales-report/",
        pasal_chart_category_sales_report,
        name="pasal_chart_category_sales_report",
    ),
]

agg = [
    path(
        "dashboard/agg/total-sales/",
        pasal_dashboard_total_sales,
        name="pasal_dashboard_total_sales",
    ),
    path(
        "dashboard/agg/average-order-value/",
        pasal_dashboard_average_order_value,
        name="pasal_dashboard_average_order_value",
    ),
    path(
        "dashboard/agg/total-customers/",
        pasal_dashboard_total_customers,
        name="pasal_dashboard_total_customers",
    ),
    path(
        "dashboard/agg/total-orders/",
        pasal_dashboard_total_orders,
        name="pasal_dashboard_total_orders",
    ),
    path(
        "dashboard/agg/top-customer/",
        pasal_dashboard_top_customer,
        name="pasal_dashboard_top_customer",
    ),
    path(
        "dashboard/agg/top-selling-product/",
        pasal_dashboard_top_selling_products,
        name="pasal_dashboard_top_selling_products",
    ),
]


tables = [
    path(
        "dashboard/table/transactions-list/",
        pasal_dashboard_transactions_list,
        name="pasal_dashboard_transactions_list",
    ),
    path(
        "table/order-list/",
        pasal_dashboard_order,
        name="pasal_dashboard_order",
    ),
]

settings = [
    path(
        "dashboard/settings/",
        pasal_settings,
        name="pasal_settings",
    ),
]

urlpatterns += ui
urlpatterns += products
urlpatterns += employees
urlpatterns += customers
urlpatterns += order
urlpatterns += charts
urlpatterns += agg
urlpatterns += tables
urlpatterns += settings
urlpatterns += sales

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.ecommerce.views import store_front
from apps.home.views import pasal_home, pasal_register

urlpatterns = [
    path("", include("apps.home.urls"), name="pasal-home"),
    path("", include("apps.ecommerce.urls"), name="ecommerce"),
]
admin_url = [
    path("admin/", admin.site.urls),
]

urlpatterns += admin_url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/ecommerce/models.py
import random
import uuid
import string


from django.db import models
from django.db.models import Sum

from django.core.exceptions import ValidationError
from django.utils.text import slugify

from apps.tenant.models import TenantAwareModel


class Customer(TenantAwareModel):
    first_name = models.CharField(max_length=244)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    mobile_number = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    stripe_id = models.CharField(max_length=255, default=None, null=True)

    # def save(self, *args, **kwargs):
    #     existing_customer = (
    #         Customer.objects.filter(email=self.email).exclude(pk=self.pk).first()
    #     )

    #     if existing_customer:
    #         raise ValidationError("Customer with this email already exists.")
    #     else:
    #         super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.tenant.name}'s Customer : {self.first_name}"


# CORE
class ProductImages(TenantAwareModel):
    images = models.ImageField(verbose_name="Product Images")

    def __str__(self):
        return f"{self.tenant.name}: {self.images.name}"


class ProductCategory(TenantAwareModel):
    name = models.CharField(verbose_name="Category", max_length=255)

    def __str__(self):
        return f"{self.tenant.name}:{self.name}"


class Products(TenantAwareModel):
    name = models.CharField(
        verbose_name="Product Name",
        max_length=255,
    )
    price = models.DecimalField(
        verbose_name="Product Price",
        max_digits=15,
        decimal_places=2,
    )  # done
    cost_price = models.DecimalField(
        verbose_name="Cost Price", max_digits=15, decimal_places=2, default=0
    )  # done

    discount = models.DecimalField(
        verbose_name="Discount",
        max_digits=15,
        decimal_places=2,
    )  # done
    stock_quantity = models.PositiveIntegerField(
        default=0, verbose_name="Stock Quantity"
    )  # done
    images = models.ManyToManyField(ProductImages)

    category = models.ManyToManyField(
        to=ProductCategory,
    )  # done

    description = models.TextField(
        verbose_name="Product Description",
    )

    slug = models.SlugField(unique=True, blank=True)

    @property
    def stock(self):
        if self.stock_quantity > 0:
            return self.stock_quantity
        else:
            return None

    @property
    def margin(self):
        margin = self.price - self.cost_price
        return margin

    def __str__(self):
        return f"{self.tenant.name}:{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug or self.name != getattr(self, "_original_name", None):
            self._original_name = self.name
            base_slug = slugify(self.name)

            # Check if the object is being created (not yet in the database)
            if not self.pk:
                slug_exists = Products.objects.filter(slug=base_slug).exists()

                if slug_exists:
                    random_suffix = "".join(
                        random.choices(string.ascii_letters + string.digits, k=6)
                    )
                    self.slug = f"{base_slug}-{random_suffix}"
                else:
                    self.slug = base_slug

        super().save(*args, **kwargs)


class CartItem(models.Model):
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE, blank=True, null=True
    )
    quantity = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.product.price * self.quantity


class Cart(TenantAwareModel):
    cart_customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True, blank=True
    )
    items = models.ManyToManyField(CartItem)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def total(self):
        return sum(item.subtotal() for item in self.items.all())

    def total_products(self):
        return self.items.count()

    def generate_stripe_line_items(self):
        line_items = []
        for cart_item in self.items.all():
            line_item = {
                "price_data": {
                    "currency": "aud",
                    "unit_amount": int(cart_item.product.price * 100),
                    "product_data": {
                        "name": cart_item.product.name,
                        "description": cart_item.product.description,
                    },
                },
                "quantity": cart_item.quantity,
            }
            line_items.append(line_item)
        return line_items

    def __str__(self):
        return f"{self.tenant.name}:{self.cart_customer.email}"


class OrderItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=15, decimal_places=2)

    def subtotal(self):
        return self.quantity * self.price


class Order(TenantAwareModel):
    status_choices = (
        ("PENDING", "Pending"),
        ("COMPLETED", "Completed"),
        ("CANCELLED", "Cancelled"),
    )
    order_customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True, blank=True
    )
    items = models.ManyToManyField(OrderItem)  # Change here
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    total_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    status = models.CharField(max_length=20, choices=status_choices, default="PENDING")
    order_number = models.CharField(max_length=36, unique=True)

    # Additional fields for shipping information, billing information, etc.
    # Add fields as per your requirement

    def generate_unique_order_number(self):
        unique_order_number = str(uuid.uuid4())
        while Order.objects.filter(order_number=unique_order_number).exists():
            unique_order_number = str(uuid.uuid4())
        return unique_order_number

    def total_amount(self):
        return sum(item.subtotal() for item in self.items.all())

    def __str__(self):
        return f"{self.tenant.name}:{self.order_customer.email}"


# UI
class RelatedProductsUI(TenantAwareModel):
    related_products = models.ManyToManyField(
        to=Products,
        verbose_name="Related Products",
    )

    def __str__(self):
        return f"{self.tenant.name} - {self.related_products}"


class FooterUI(TenantAwareModel):
    instagram = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.tenant.name} : Socials"


class TopBarUI(TenantAwareModel):
    text = models.TextField()

    def __str__(self) -> str:
        return f"{self.tenant.name}:topbar"


class ImageWithTextUI(TenantAwareModel):
    overlay_image = models.ImageField()
    overlay_text = models.CharField(max_length=255, verbose_name="Text Image Overlay")


class CategoryUI(TenantAwareModel):
    category = models.ForeignKey(
        to=ProductCategory,
        verbose_name="Category to show",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return f"{self.tenant.name}:categoryUI"


class FeaturedProductsUI(TenantAwareModel):
    products = models.ManyToManyField(to=Products, verbose_name="Featured Products")

    def __str__(self):
        return f"{self.tenant.name}:featuredProductsUI"

src/apps/home/models.py
from django.db import models

# Create your models here.

src/apps/tenant/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver

from apps.user.models import CustomUser


class Tenant(models.Model):
    name = models.CharField(max_length=255)
    subdomain = models.CharField(max_length=255)
    stripe_id = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name


class TenantAwareQuerySet(models.QuerySet):
    def filter_by_tenant(self, tenant):
        return self.filter(tenant=tenant)


class TenantAwareManager(models.Manager):
    def get_queryset(self):
        base_queryset = super().get_queryset()
        if hasattr(self.model, "tenant") and hasattr(self.model.tenant, "identifier"):
            return base_queryset.filter_by_tenant(self.model.tenant)
        return base_queryset


class TenantAwareModel(models.Model):
    tenant = models.ForeignKey(Tenant, on_delete=models.CASCADE)


class Employees(TenantAwareModel):
    user = models.OneToOneField(
        to=CustomUser, on_delete=models.CASCADE, related_name="employee"
    )
    is_owner = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} - {self.tenant.name}"


class StoreInformation(TenantAwareModel):
    email = models.EmailField(null=True, blank=True, default="null@null.com")
    about_us = models.TextField(default="null")
    contact = models.TextField(default="null")
    address = models.CharField(max_length=233, default="null")
    logo = models.ImageField(default="null")
    favicon = models.ImageField(null=True, blank=True, default="null")

    def __str__(self):
        return f"{self.tenant.name}'s Information"


@receiver(post_save, sender=Tenant)
def create_store_information(sender, instance, created, **kwargs):
    if created:
        StoreInformation.objects.create(tenant=instance)

src/apps/home/templates/dashboard/tenant_base.html
<!DOCTYPE html>
<html lang="en">
      <head>
            <meta name="title" content="Google">
            <meta name="description"
                  content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.">
            <meta property="og:type" content="website">
            <meta property="og:url" content="https://www.google.com/">
            <meta property="og:title" content="Google">
            <meta property="og:description"
                  content="Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.">
            <meta property="og:image" content="">
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>
                  {% block title %}
                  {% endblock title %}
            </title>
            {% comment %} quill {% endcomment %}
            <script src="https://cdn.ckeditor.com/ckeditor5/41.0.0/classic/ckeditor.js"></script>
            {% comment %} tailwind {% endcomment %}
            <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css"
                  rel="stylesheet">
            <link rel="stylesheet"
                  href="https://unpkg.com/tailwindcss@2.2.19/dist/utilities.min.css">
            <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/typography/src/index.min.js"></script>
            {% comment %} flowbite {% endcomment %}
            <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.css"
                  rel="stylesheet" />
            <script src="https://cdn.jsdelivr.net/npm/flowbite-typography@1.0.3/src/index.min.js"></script>
            <link rel="stylesheet"
                  href="https://cdn.jsdelivr.net/npm/flowbite-typography@1.0.3/dist/typography.min.css"
                  integrity="sha256-0PTpzcFyf4L2OLKO8+xCBFK9ZABMRPVkxu6y0yM2RiU="
                  crossorigin="anonymous">
            {% comment %} toastify {% endcomment %}
            <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/toastify-js"></script>
            <link rel="stylesheet"
                  type="text/css"
                  href="https://cdn.jsdelivr.net/npm/toastify-js/src/toastify.min.css">
            {% comment %} hyperscript {% endcomment %}
            <script src="https://unpkg.com/hyperscript.org@0.9.12"></script>
            {% comment %} htmx {% endcomment %}
            <script src="https://unpkg.com/htmx.org@1.9.9"></script>
            {% comment %} jquery {% endcomment %}
            <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
            {% comment %} select2 {% endcomment %}
            <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css"
                  rel="stylesheet" />
            <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
            {% comment %} charts plotly {% endcomment %}
            <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
            {% block style %}
            {% endblock style %}
      </head>
      {% include "dashboard/partials/sidebar.html" %}
      <body onload="displayDjangoMessages()">
            <div class="p-4 sm:ml-64 mt-14">
                  <main>
                        {% include "partials/messages.html" %}
                        {% block content %}
                        {% endblock content %}
                  </main>
            </div>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.0/flowbite.min.js"></script>
      </body>
      {% block script %}
      {% endblock script %}
      <script></script>
</html>

src/apps/home/templates/dashboard/tenant_detail_customer.html
{% extends "dashboard/tenant_base.html" %}
{% block content %}
    <div class="container mx-auto px-4 py-8">
        <div class="max-w-2xl mx-auto">
            <h2 class="text-2xl font-semibold mb-4">Customer Details</h2>
            <div class="bg-white shadow overflow-hidden sm:rounded-lg">
                <div class="px-4 py-5 sm:px-6">
                    <h3 class="text-lg leading-6 font-medium text-gray-900">Customer Information</h3>
                </div>
                <div class="border-t border-gray-200">
                    <dl>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">First Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2">
                                {{ customer.first_name }}
                            </dd>
                        </div>
                        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Last Name</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2">
                                {{ customer.last_name }}
                            </dd>
                        </div>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Email</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2">
                                {{ customer.email }}
                            </dd>
                        </div>
                        <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Mobile Number</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2">
                                {{ customer.mobile_number }}
                            </dd>
                        </div>
                        <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                            <dt class="text-sm font-medium text-gray-500">Address</dt>
                            <dd class="mt-1 text-sm text-gray-900 sm:col-span-2">
                                {{ customer.address }}
                            </dd>
                        </div>
                        <!-- Add more fields as needed -->
                    </dl>
                </div>
            </div>
  <div class="mt-8 grid grid-cols-1 sm:grid-cols-2 gap-4">
    {% for order in customer.order_set.all %}
    <div>
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="px-4 py-5 sm:px-6">
                <h3 class="text-lg leading-6 font-medium text-gray-900">Order Information</h3>
                <p class="mt-1 text-sm text-gray-500">Order Number: {{ order.order_number }}</p>
            </div>
            <div class="border-t border-gray-200">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Product
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Quantity
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Price
                            </th>
                            <th scope="col"
                                class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Subtotal
                            </th>
                        </tr>
                    </thead>
                    <tbody class="bg-white divide-y divide-gray-200">
                        {% for item in order.items.all %}
                        <tr>
                            <td class="px-6 py-4 whitespace-nowrap">{{ item.product.name }}</td>
                            <td class="px-6 py-4 whitespace-nowrap">{{ item.quantity }}</td>
                            <td class="px-6 py-4 whitespace-nowrap">{{ item.price }}</td>
                            <td class="px-6 py-4 whitespace-nowrap">{{ item.subtotal }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="px-4 py-4 sm:px-6">
                <p class="mt-1 text-sm text-gray-500">Total Amount: ${{ order.total_amount }}</p>
                <form hx-post="{% url 'update_order_status' order.id %}" hx-indicator="#indicator-{{ forloop.counter }}" method="post"
                    action="{% url 'update_order_status' order.id %}">
                    {% csrf_token %}
                    <div class="mt-4">
                        <label for="order_status" class="block text-sm font-medium text-gray-700">Change Status:</label>
                        <select id="staorder_statustus" name="order_status"
                            class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                            <option value="Pending" {% if order.status == 'Pending' %}selected{% endif %}>Pending</option>
                            <option value="Processing" {% if order.status == 'Processing' %}selected{% endif %}>Processing</option>
                            <option value="Shipped" {% if order.status == 'Shipped' %}selected{% endif %}>Shipped</option>
                            <option value="Delivered" {% if order.status == 'Delivered' %}selected{% endif %}>Delivered</option>
                        </select>
                    </div>
                    <button type="submit"
                        class="mt-3 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center me-2 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 inline-flex items-center">
                        Update Status
                    </button>
                </form>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

        </div>
    </div>
{% endblock content %}

src/apps/home/templates/dashboard/tenant_edit_employees.html
{% extends "dashboard/tenant_base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="container mx-auto mt-8">
        <h2 class="text-2xl font-bold mb-4">Edit Employee</h2>
        <form method="post" class="max-w-lg mx-auto" enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form | crispy }}
            <div class="mt-4">
                <button type="submit"
                        class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">Update</button>
                <a href="{% url 'list-employees' %}"
                   class="ml-2 text-gray-600 hover:text-gray-800">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

src/apps/home/templates/dashboard/tenant_list_customers.html
c{% extends "dashboard/tenant_base.html" %}
{% block content %}
    <div class="container mx-auto px-4 py-8">
        <h2 class="text-2xl font-semibold mb-4">Registered Customers</h2>
        <div class="overflow-x-auto">
            <table class="table-auto min-w-full border-collapse border border-gray-300">
                <thead>
                    <tr>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">First Name</th>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">Last Name</th>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">Email</th>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">Mobile Number</th>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">Address</th>
                        <th class="px-4 py-2 bg-gray-100 border border-gray-300">Customer Detail</th>
                        <!-- Add more table headers if needed -->
                    </tr>
                </thead>
                <tbody>
                    {% for customer in customers %}
                        <tr>
                            <td class="px-4 py-2 border border-gray-300">{{ customer.first_name }}</td>
                            <td class="px-4 py-2 border border-gray-300">{{ customer.last_name }}</td>
                            <td class="px-4 py-2 border border-gray-300">{{ customer.email }}</td>
                            <td class="px-4 py-2 border border-gray-300">{{ customer.mobile_number }}</td>
                            <td class="px-4 py-2 border border-gray-300">{{ customer.address }}</td>
                            <td class="px-4 py-2 border border-gray-300 text-red-600 underline">
                                <a href="{% url "pasal-detail-customers" customer.id %}">View Detail</a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock content %}

src/apps/home/templates/dashboard/tenant_sales.html
{% extends "tenant_base.html" %}
{% block content %}
    {{ request.user }}
    {{ request.user.first_name }} {{ request.user.last_name }}
    {{ request.user.tenant.name }}
    Sales
{% endblock content %}

src/apps/home/templates/dashboard/tenant_settings.html
{% extends "dashboard/tenant_base.html" %}
{% block content %}
    Settings
    <form action="">
    </form>
{% endblock content %}

src/apps/home/templates/dashboard/tenant_store_information_layout.html
{% extends "dashboard/tenant_base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block script %}
    <script>
    ClassicEditor
        .create(document.querySelector('#id_about_us'), {
            mediaEmbed: {
                previewsInData: true
            }
        })
        .catch(error => {
            console.error(error);
        });
    </script>
{% endblock script %}
{% block content %}
    <style>
    .resizer {
        display: flex;
        margin: 0;
        padding: 0;
        resize: horizontal;
        overflow: hidden
    }

    .resizer>.resized {
        flex-grow: 1;
        margin: 0;
        padding: 0;
        border: 0
    }

    .ugly {
        border-color: pink;
    }
    </style>
    <div class="grid grid-cols-2 gap-4">
        <div class="resizer ugly">
            <iframe class="resized"
                    id="resizableDiv"
                    src="http://{{ tenant }}.localhost:8000/about-us"
                    frameborder="5"
                    height="1000"></iframe>
        </div>
        <div>
            <form method="post" enctype="multipart/form-data" hx-boost="false">
                {% csrf_token %}
                <div id="toolbar"></div>
                {{ form | crispy }}
                <button type="submit">Add Information</button>
            </form>
        </div>
    </div>
{% endblock content %}