src/apps/home/urls.py
from django.urls import path

from apps.home.views import (
    pasal_home,
    pasal_register,
    pasal_tac,
    # dashboard
    pasal_dashboard_login,
    pasal_dashboard_logout,
    pasal_dashboard_sales,
    pasal_dashboard,
    # agg views
    pasal_dashboard_total_sales,
    pasal_dashboard_average_order_value,
    pasal_dashboard_top_customer,
    pasal_dashboard_top_selling_products,
    pasal_dashboard_total_customers,
    pasal_dashboard_total_orders,
    pasal_dashboard_transactions_list,
    pasal_dashboard_order,
    # ui
    pasal_ui_storefront_layout,
    pasal_ui_store_information,
    # products
    pasal_create_product,
    pasal_create_product_image,
    pasal_create_product_category,
    pasal_list_products,
    pasal_edit_product,
    pasal_delete_product,
    # employees
    pasal_list_employees,
    pasal_create_employees,
    pasal_edit_employee,
    pasal_delete_employee,
    # settings
    pasal_settings,
    # customers
    pasal_list_customers,
    pasal_detail_customers,
    # order
    pasal_update_order_status,
    # charts
    pasal_chart_sales_report,
    pasal_chart_category_sales_report,
)

urlpatterns = [
    path(
        "home/",
        pasal_home,
        name="pasal_home",
    ),
    path(
        "terms-and-conditions",
        pasal_tac,
        name="pasal_terms_and_conditions",
    ),
    path(
        "register/",
        pasal_register,
        name="pasal-register-tenant",
    ),
    path(
        "login/",
        pasal_dashboard_login,
        name="pasal-dashboard-login",
    ),
    path(
        "logout/",
        pasal_dashboard_logout,
        name="pasal-dashboard-logout",
    ),
    path(
        "dashboard/",
        pasal_dashboard,
        name="pasal-dashboard",
    ),
]

sales = [
    path(
        "dashboard/sales/",
        pasal_dashboard_sales,
        name="pasal-dashboard-sales",
    ),
]

products = [
    path(
        "dashboard/products/add/",
        pasal_create_product,
        name="pasal_create_product",
    ),
    path(
        "dashboard/products/list/<int:page>/",
        pasal_list_products,
        name="pasal_list_product",
    ),
    path(
        "dashboard/products/edit/<slug:slug>/",
        pasal_edit_product,
        name="pasal_edit_product",
    ),
    path(
        "dashboard/products/delete/<slug:slug>/",
        pasal_delete_product,
        name="pasal_delete_product",
    ),
    path(
        "dashboard/products/add/image/",
        pasal_create_product_image,
        name="pasal_create_product_image",
    ),
    path(
        "dashboard/products/add/category/",
        pasal_create_product_category,
        name="pasal_create_category",
    ),
]

ui = [
    path(
        "dashboard/ui/storefront/",
        pasal_ui_storefront_layout,
        name="pasal_dashboard_storefront_ui",
    ),
    path(
        "dashboard/ui/products/",
        pasal_ui_storefront_layout,
        name="pasal-dashboard-ui-product-page",
    ),
    path(
        "dashboard/storeinformation/",
        pasal_ui_store_information,
        name="pasal_store_information",
    ),
]

customers = [
    path(
        "dashboard/customers/list/",
        pasal_list_customers,
        name="pasal-list-customers",
    ),
    path(
        "dashboard/customers/<int:customer_id>/",
        pasal_detail_customers,
        name="pasal-detail-customers",
    ),
]

employees = [
    path(
        "dashboard/employees/list/",
        pasal_list_employees,
        name="list-employees",
    ),
    path(
        "employees/create/",
        pasal_create_employees,
        name="create-employees",
    ),
    path(
        "employees/<int:employee_id>/edit/",
        pasal_edit_employee,
        name="edit-employee",
    ),
    path(
        "dashboard/employees/<int:employee_id>/delete/",
        pasal_delete_employee,
        name="delete-employee",
    ),
]


order = [
    path(
        "dashboard/order/<int:order_id>/update/",
        pasal_update_order_status,
        name="update_order_status",
    ),
]


charts = [
    path(
        "dashboard/charts/sales-report/",
        pasal_chart_sales_report,
        name="pasal_charts_sales_report",
    ),
    path(
        "dashboard/charts/category-sales-report/",
        pasal_chart_category_sales_report,
        name="pasal_chart_category_sales_report",
    ),
]

agg = [
    path(
        "dashboard/agg/total-sales/",
        pasal_dashboard_total_sales,
        name="pasal_dashboard_total_sales",
    ),
    path(
        "dashboard/agg/average-order-value/",
        pasal_dashboard_average_order_value,
        name="pasal_dashboard_average_order_value",
    ),
    path(
        "dashboard/agg/total-customers/",
        pasal_dashboard_total_customers,
        name="pasal_dashboard_total_customers",
    ),
    path(
        "dashboard/agg/total-orders/",
        pasal_dashboard_total_orders,
        name="pasal_dashboard_total_orders",
    ),
    path(
        "dashboard/agg/top-customer/",
        pasal_dashboard_top_customer,
        name="pasal_dashboard_top_customer",
    ),
    path(
        "dashboard/agg/top-selling-product/",
        pasal_dashboard_top_selling_products,
        name="pasal_dashboard_top_selling_products",
    ),
]


tables = [
    path(
        "dashboard/table/transactions-list/",
        pasal_dashboard_transactions_list,
        name="pasal_dashboard_transactions_list",
    ),
    path(
        "table/order-list/",
        pasal_dashboard_order,
        name="pasal_dashboard_order",
    ),
]

settings = [
    path(
        "dashboard/settings/",
        pasal_settings,
        name="pasal_settings",
    ),
]

urlpatterns += ui
urlpatterns += products
urlpatterns += employees
urlpatterns += customers
urlpatterns += order
urlpatterns += charts
urlpatterns += agg
urlpatterns += tables
urlpatterns += settings
urlpatterns += sales

src/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from apps.ecommerce.views import store_front
from apps.home.views import pasal_home, pasal_register

urlpatterns = [
    path("", include("apps.home.urls"), name="pasal-home"),
    path("", include("apps.ecommerce.urls"), name="ecommerce"),
]
admin_url = [
    path("admin/", admin.site.urls),
]

urlpatterns += admin_url
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/ecommerce/models.py
import random
import uuid
import string


from django.db import models
from django.db.models import Sum

from django.core.exceptions import ValidationError
from django.utils.text import slugify

from apps.tenant.models import TenantAwareModel


class Customer(TenantAwareModel):
    first_name = models.CharField(max_length=244)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    mobile_number = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    stripe_id = models.CharField(max_length=255, default=None, null=True)

    # def save(self, *args, **kwargs):
    #     existing_customer = (
    #         Customer.objects.filter(email=self.email).exclude(pk=self.pk).first()
    #     )

    #     if existing_customer:
    #         raise ValidationError("Customer with this email already exists.")
    #     else:
    #         super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.tenant.name}'s Customer : {self.first_name}"


# CORE
class ProductImages(TenantAwareModel):
    images = models.ImageField(verbose_name="Product Images")

    def __str__(self):
        return f"{self.tenant.name}: {self.images.name}"


class ProductCategory(TenantAwareModel):
    name = models.CharField(verbose_name="Category", max_length=255)

    def __str__(self):
        return f"{self.tenant.name}:{self.name}"


class Products(TenantAwareModel):
    name = models.CharField(
        verbose_name="Product Name",
        max_length=255,
    )
    price = models.DecimalField(
        verbose_name="Product Price",
        max_digits=15,
        decimal_places=2,
    )  # done
    cost_price = models.DecimalField(
        verbose_name="Cost Price", max_digits=15, decimal_places=2, default=0
    )  # done

    discount = models.DecimalField(
        verbose_name="Discount",
        max_digits=15,
        decimal_places=2,
    )  # done
    stock_quantity = models.PositiveIntegerField(
        default=0, verbose_name="Stock Quantity"
    )  # done
    images = models.ManyToManyField(ProductImages)

    category = models.ManyToManyField(
        to=ProductCategory,
    )  # done

    description = models.TextField(
        verbose_name="Product Description",
    )

    slug = models.SlugField(unique=True, blank=True)

    @property
    def stock(self):
        if self.stock_quantity > 0:
            return self.stock_quantity
        else:
            return None

    @property
    def margin(self):
        margin = self.price - self.cost_price
        return margin

    def __str__(self):
        return f"{self.tenant.name}:{self.name}"

    def save(self, *args, **kwargs):
        if not self.slug or self.name != getattr(self, "_original_name", None):
            self._original_name = self.name
            base_slug = slugify(self.name)

            # Check if the object is being created (not yet in the database)
            if not self.pk:
                slug_exists = Products.objects.filter(slug=base_slug).exists()

                if slug_exists:
                    random_suffix = "".join(
                        random.choices(string.ascii_letters + string.digits, k=6)
                    )
                    self.slug = f"{base_slug}-{random_suffix}"
                else:
                    self.slug = base_slug

        super().save(*args, **kwargs)


class CartItem(models.Model):
    product = models.ForeignKey(
        Products, on_delete=models.CASCADE, blank=True, null=True
    )
    quantity = models.PositiveIntegerField(default=1)

    def subtotal(self):
        return self.product.price * self.quantity


class Cart(TenantAwareModel):
    cart_customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True, blank=True
    )
    items = models.ManyToManyField(CartItem)
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def total(self):
        return sum(item.subtotal() for item in self.items.all())

    def total_products(self):
        return self.items.count()

    def generate_stripe_line_items(self):
        line_items = []
        for cart_item in self.items.all():
            line_item = {
                "price_data": {
                    "currency": "aud",
                    "unit_amount": int(cart_item.product.price * 100),
                    "product_data": {
                        "name": cart_item.product.name,
                        "description": cart_item.product.description,
                    },
                },
                "quantity": cart_item.quantity,
            }
            line_items.append(line_item)
        return line_items

    def __str__(self):
        return f"{self.tenant.name}:{self.cart_customer.email}"


class OrderItem(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.DecimalField(max_digits=15, decimal_places=2)

    def subtotal(self):
        return self.quantity * self.price


class Order(TenantAwareModel):
    status_choices = (
        ("PENDING", "Pending"),
        ("COMPLETED", "Completed"),
        ("CANCELLED", "Cancelled"),
    )
    order_customer = models.ForeignKey(
        Customer, on_delete=models.CASCADE, null=True, blank=True
    )
    items = models.ManyToManyField(OrderItem)  # Change here
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    total_amount = models.DecimalField(max_digits=15, decimal_places=2, default=0)

    status = models.CharField(max_length=20, choices=status_choices, default="PENDING")
    order_number = models.CharField(max_length=36, unique=True)

    # Additional fields for shipping information, billing information, etc.
    # Add fields as per your requirement

    def generate_unique_order_number(self):
        unique_order_number = str(uuid.uuid4())
        while Order.objects.filter(order_number=unique_order_number).exists():
            unique_order_number = str(uuid.uuid4())
        return unique_order_number

    def total_amount(self):
        return sum(item.subtotal() for item in self.items.all())

    def __str__(self):
        return f"{self.tenant.name}:{self.order_customer.email}"


# UI
class RelatedProductsUI(TenantAwareModel):
    related_products = models.ManyToManyField(
        to=Products,
        verbose_name="Related Products",
    )

    def __str__(self):
        return f"{self.tenant.name} - {self.related_products}"


class FooterUI(TenantAwareModel):
    instagram = models.URLField(null=True, blank=True)
    facebook = models.URLField(null=True, blank=True)

    def __str__(self):
        return f"{self.tenant.name} : Socials"


class TopBarUI(TenantAwareModel):
    text = models.TextField()

    def __str__(self) -> str:
        return f"{self.tenant.name}:topbar"


class ImageWithTextUI(TenantAwareModel):
    overlay_image = models.ImageField()
    overlay_text = models.CharField(max_length=255, verbose_name="Text Image Overlay")


class CategoryUI(TenantAwareModel):
    category = models.ForeignKey(
        to=ProductCategory,
        verbose_name="Category to show",
        on_delete=models.SET_NULL,
        null=True,
    )

    def __str__(self):
        return f"{self.tenant.name}:categoryUI"


class FeaturedProductsUI(TenantAwareModel):
    products = models.ManyToManyField(to=Products, verbose_name="Featured Products")

    def __str__(self):
        return f"{self.tenant.name}:featuredProductsUI"

src/apps/home/models.py
from django.db import models

# Create your models here.

src/apps/home/templates/dashboard/products/tenant_create_product.html
{% extends "dashboard/tenant_base.html" %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <section class="bg-white dark:bg-gray-900">
            <div class="py-8 px-4 mx-auto max-w-2xl lg:py-16">
                <h2 class="mb-4 text-xl font-bold text-gray-900 dark:text-white">Add a new product</h2>
                <form action="#">
                    <div class="grid gap-4 sm:grid-cols-2 sm:gap-6">
                        <div class="sm:col-span-3">
                            <label for="name"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.name.label }}
                            </label>
                            {% render_field form.name type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="Type product name" %}
                        </div>
                        <div class="w-full">
                            <label for="brand"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.price.label }}
                            </label>
                            {% render_field form.price class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" min="1" %}
                        </div>
                        <div class="w-full">
                            <label for="price"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.cost_price.label }}
                            </label>
                            {% render_field form.cost_price class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" placeholder="2999" min="1" %}
                        </div>
                        <div>
                            <label for="category"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.category.label }}
                            </label>
                            {% render_field form.category name="category" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-500 focus:border-primary-500 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %}
                        </div>
                        <div>
                            <label for="item-weight"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.stock_quantity.label }}
                            </label>
                            {% render_field form.stock_quantity class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" min="1" %}
                        </div>
                        <div class="sm:col-span-1">
                            <label for="description"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.discount.label }}
                            </label>
                            {% render_field form.discount class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" min="0" max="100" %}
                        </div>
                        <div class="sm:col-span-1">
                            <label for="description"
                                   class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                                {{ form.images.label }}
                            </label>
                            {% render_field form.images name="images" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %}
                        </div>
                    </div>
                    <label for="description"
                           class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">
                        {{ form.description.label }}
                    </label>
                    {% render_field form.description class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-primary-600 focus:border-primary-600 block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500" %}
                    <br>
                    <button type="submit"
                            class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">
                        Add product
                    </button>
                    <br>
                </form>
                {% comment %} button {% endcomment %}
                <div class="flex">
                    <button hx-boost="false"
                            data-modal-target="create_product-modal"
                            data-modal-toggle="create_product-modal"
                            class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                            type="button">Add Image</button>
                    &nbsp
                    <button hx-boost="false"
                            data-modal-target="create_category-modal"
                            data-modal-toggle="create_category-modal"
                            class="block text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800"
                            type="button">Add Category</button>
                </div>
            </div>
        </section>
    </form>
    {% include "dashboard/partials/tenant_create_product_image.html" %}
    {% include "dashboard/partials/tenant_create_product_category.html" %}
{% endblock content %}
{% block script %}
    <script>
    $(document).ready(function() {
    $('#id_category').select2();
    $('#id_images').select2();
});
    </script>
{% endblock script %}

src/apps/home/templates/dashboard/products/tenant_list_products.html
{% extends "dashboard/tenant_base.html" %}
{% load util_tags %}
{% block content %}
    <h1 class="text-xl font-bold pb-10">
        Products
        <span hx-boost="false">
            <a href="{% url 'pasal_create_product' %}"
               class="text-white bg-green-700 rounded ml-2 px-1 py-1">add +</a>
        </span>
    </h1>
    <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
        <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
            <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                <tr>
                    <th scope="col" class="px-6 py-3">SN</th>
                    <th scope="col" class="px-6 py-3">Product name</th>
                    <th scope="col" class="px-6 py-3">Product image</th>
                    <th scope="col" class="px-6 py-3">Category</th>
                    <th scope="col" class="px-6 py-3">Stock</th>
                    <th scope="col" class="px-6 py-3">Selling Price</th>
                    <th scope="col" class="px-6 py-3">Cost Price</th>
                    <th scope="col" class="px-6 py-3">Margin</th>
                    <th scope="col" class="px-6 py-3">Delete</th>
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
                        <td class="px-6 py-4">{{ forloop.counter }}</td>
                        <td class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">{{ product.name }}</td>
                        <td class="px-6 py-4">
                            <img src="{{ product.images.first.images.url }}"
                                 alt="{{ product.name }}"
                                 height="200"
                                 width="200">
                        </td>
                        <td class="px-6 py-4">
                            {% for category in product.category.all %}
                                <span class="bg-blue-100 text-blue-800 text-xs font-medium me-2 px-2.5 py-0.5 rounded dark:bg-blue-900 dark:text-blue-300">{{ category.name }}</span>
                            {% endfor %}
                        </td>
                        <td class="px-6 py-4">{{ product.stock }}</td>
                        <td class="px-6 py-4">{{ product.price }}</td>
                        <td class="px-6 py-4">{{ product.cost_price }}</td>
                        <td class="px-6 py-4">{{ product.margin }}</td>
                        <td class="px-6 py-4">
                            <a href="{% url 'pasal_edit_product' product.slug %}"
                               class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Edit</a>
                        </td>
                        <td class="px-6 py-4">
                            <a hx-confirm="Delete {{ product.name }} ?"
                               hx-get="{% url 'pasal_delete_product' product.slug %}"
                               class="font-medium text-red-600 dark:text-red-500 hover:underline">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <nav class="flex items-center flex-column flex-wrap md:flex-row justify-between pt-4"
             aria-label="Table navigation">
            <span class="ml-3 mb-3 text-sm font-normal text-gray-500 dark:text-gray-400 mb-4 md:mb-0 block w-full md:inline md:w-auto">Showing Page <span class="font-semibold text-gray-900 dark:text-white">{{ products.number }}</span> of <span class="font-semibold text-gray-900 dark:text-white">{{ products.paginator.num_pages }}</span></span>
            <ul class="inline-flex -space-x-px rtl:space-x-reverse text-sm h-8 mb-3 mr-3">
                <li>
                    {% if products.has_previous %}
                        <a href="{% url 'pasal_list_product' products.previous_page_number %}"
                           class="flex items-center justify-center px-3 h-8 ms-0 leading-tight text-gray-500 bg-white border border-gray-300 rounded-l-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Previous</a>
                    {% endif %}
                </li>
                {% for page in products.paginator.page_range %}
                    <li>
                        <a href="{% url 'pasal_list_product' page %}"
                           class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">{{ page }}</a>
                    </li>
                {% endfor %}
                <li>
                    {% if products.has_next %}
                        <a href="{% url 'pasal_list_product' products.next_page_number %}"
                           class="flex items-center justify-center px-3 h-8 leading-tight text-gray-500 bg-white border border-gray-300 rounded-r-lg hover:bg-gray-100 hover:text-gray-700 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white">Next</a>
                    {% endif %}
                </li>
            </ul>
        </nav>
    </div>
{% endblock content %}